# Generated by Django 2.2.4 on 2019-11-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fatwas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('muftee', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'fatwas',
                'db_table': 'fatwas',
                'managed': False,
            },
        ),
    ]
